language: c
dist: xenial
sudo: false
compiler: gcc
os: linux

env: COMPILER=gcc-7 CODE_COVERAGE=true CMAKE_BUILD_TYPE=Debug BUILD_DIRECTORY=cmake-build-debug

cache: # see https://docs.travis-ci.com/user/caching/
  - directories:
      - $HOME/.cache

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq gcc-7
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 90
  - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-7 90
  - sudo apt-get install -qq -y lcov
  - sudo apt-get install -qq -y ruby
  - sudo gem install coveralls-lcov
  - export CC="${COMPILER}"

before_script:
  - ${CC} --version
  - cmake --version
  - lcov --version
  - gcov --version

script:
  - mkdir -p ${BUILD_DIRECTORY} && cd ${BUILD_DIRECTORY} || exit 1
  - cmake .. || exit 1
  - cmake --build . --target code_kata || exit 1
  - code_kata || exit 1